### ISSUE TITLE
Server crash with Cannot set property DirectionProperty

### ISSUE THREAD

**Issue by thvless** [copycats-plus/copycats#37]
running copycats 1.18.2-1.2.0 on forge 40.2.4

the server loads up just fine but as soon as i join the server shuts down

server log:
[latest.log](https://github.com/copycats-plus/copycats/files/14749944/latest.log)

crash report:
[crash-2024-03-25_21.48.26-server.txt](https://github.com/copycats-plus/copycats/files/14749951/crash-2024-03-25_21.48.26-server.txt)

client log:
[latest.log](https://github.com/copycats-plus/copycats/files/14749964/latest.log)

**Comment by thvless** [comment]
i must also add that it crashes and doesnt release session.lock making it seem like the server is still running meaning i have to restart the VM to make it work

**Comment by Bennyboy1695** [comment]
Issue should be fixed in the latest version

**Comment by thvless** [comment]
issue is still present in copycats 1.18.2-1.2.5 lol
reproduced in the same exact way, server crashes on join

log: 
[latest.log](https://github.com/copycats-plus/copycats/files/14782819/latest.log)
 
crash report:
[crash-2024-03-28_01.20.31-server.txt](https://github.com/copycats-plus/copycats/files/14782823/crash-2024-03-28_01.20.31-server.txt)

**Comment by Bennyboy1695** [comment]
That crash isnt a copycats issue its a create connected issue. Which is likely fixed already as you are on an old version of that mod
